### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by fermicro** [urutu/Urutu#23]
I'm having the following errors trying to run the sample code in your git main page:

Python 3 (done 2to3):

In Urutu\cl\__init__.py line 422
if sentence.split('\t'))>1: ##TypeError: '>' not supported between instances of 'list' and 'int'

if bypassed, will also give the same error below.

Python 2:

Traceback (most recent call last):
  File "D:\tcc\urutu_WinPython-64bit-3.6.0.1Qt5\sample.py.bak", line 35, in <module>
    print "Running on OpenCL.. \n", divmul([100,1,1], [1,1,1], a, b, c, d)
  File "D:\tcc\WinPython-64bit-2.7.10.3\python-2.7.10.amd64\lib\Urutu\__init__.py", line 30, in inner
    return cl_.execute()
  File "D:\tcc\WinPython-64bit-2.7.10.3\python-2.7.10.amd64\lib\Urutu\cl\__init__.py", line 612, in execute
    tmp.start(self.args,self.arg_nam, self.arg_mask)
  File "D:\tcc\WinPython-64bit-2.7.10.3\python-2.7.10.amd64\lib\Urutu\cl\execl.py", line 61, in start
    self.cl_args.append(cl.Buffer(self.ctx,self.mf.READ_WRITE | self.mf.COPY_HOST_PTR, hostbuf = self.args[i]))
NameError: global name 'cl' is not defined

Can you help?

**Comment by aditya4d** [comment]
Can you try changing this line https://github.com/urutu/Urutu/blob/master/Urutu/cl/__init__.py#L422

to 
```python
if len(sentence.split('\t'))>1:
```

**Comment by fermicro** [comment]
That will work to bypass the first error. So the second error will show.

**Comment by aditya4d** [comment]
I haven't tried opencl in a while and I didn't actively updated its backend to work efficiently as CUDA. I'll try to reproduce the error.
